#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$1" != "" ]; then
    BACKUP_NAME="$1"
else
    BACKUP_NAME="$( date +%Y%m%d-%H%M%S )"
fi

for SITE_NAME in empty bricks paragraphs
do
    echo -e "\nBacking up $SITE_NAME\n"

    cd $DIR/../..

    DB_FILE="backup/db-$SITE_NAME-$BACKUP_NAME.sql"
    FILES_FILE="backup/files-$SITE_NAME-$BACKUP_NAME.zip"

    fin db dump --db=$SITE_NAME $DB_FILE >/dev/null 2>&1
    cd docroot/sites/$SITE_NAME
    zip -qr ../../../$FILES_FILE files

    echo -e "\nBackup files:\n\
        Database: $DB_FILE\n\
        Files:    $FILES_FILE\n"
done
